In [70]:
!uv pip install numpy pandas matplotlib nltk pythainlp scikit-learn

Using Python 3.11.15 environment at: /home/kami/Projects/NLP/.venv
Checked 6 packages in 11ms

In [71]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /home/kami/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/kami/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/kami/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [72]:
train = pd.read_csv('./financial-news-data/financial-news-train.csv', encoding='utf-8')
test = pd.read_csv('./financial-news-data/financial-news-test.csv', encoding='utf-8')

In [73]:
def clean_text_dataframe(df, drop_duplicates=True):
    # Lowercase
    df['text'] = df['text'].str.lower()

    # Remove quotes
    df['text'] = df['text'].str.replace('"', '', regex=False)

    # Remove links
    df['text'] = df['text'].str.replace(r'https?://\S+', '', regex=True)

    # Remove words that don't start with an alphabetic character
    df['text'] = df['text'].str.replace(r'\b[^a-z\s]\S*', '', regex=True)

    # Remove non-alphabetic characters
    df['text'] = df['text'].str.replace(r'[^a-z\s]', '', regex=True)

    # Normalize whitespace after removals
    df['text'] = df['text'].str.replace(r'\s+', ' ', regex=True).str.strip()

    if drop_duplicates:
        df.drop_duplicates(subset=['text'], inplace=True)

    # NLTK remove stopwods
    stop_words = set(stopwords.words('english'))
    df['text'] = df['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

In [74]:
# Show full text
pd.set_option('display.max_colwidth', None)

clean_text_dataframe(train)
clean_text_dataframe(test, drop_duplicates=False)

train

,text,label
0,thursday biggest analyst calls apple amazon tesla palantir docusign exxon amp,Analyst Update
1,buy las vegas sands travel singapore builds wells fargo says,Analyst Update
2,piper sandler downgrades docusign sell citing elevated risks amid ceo transition,Analyst Update
3,analysts react tesla latest earnings break next electric car maker,Analyst Update
4,netflix peers set return growth analysts say giving one stock upside,Analyst Update
...,...,...
16984,china developers face wall dollar bond payments second half,Treasuries | Corporate Debt
16985,kfw credit line uniper could raised bln eur handelsblatt,Treasuries | Corporate Debt
16987,russian sells bln roubles one repo auction,Treasuries | Corporate Debt
16988,global esg bond issuance posts h dip supranationals cut back,Treasuries | Corporate Debt
16989,brazil petrobras says signed billion sustainability loan,Treasuries | Corporate Debt

In [75]:
# vocabs = set()

# for text in train.text:
#     vocabs.update(text.split())

# print(len(vocabs))
# print(vocabs)

In [76]:
# Create empty feature vectors
# features = pd.DataFrame(np.zeros((len(train), len(vocabs)), dtype=int), columns=sorted(vocabs), index=train.index)

In [77]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(vocabulary=sorted(vocabs))

X_train = vectorizer.fit_transform(train['text'])
X_test = vectorizer.transform(test['text'])

In [78]:
vectorizer.get_feature_names_out()

array(['aa', 'aad', 'aaic', ..., 'zynx', 'zyus', 'zyversa'],
      shape=(21202,), dtype=object)

In [79]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_train = encoder.fit_transform(train['label'])
y_test = encoder.transform(test['label'])

In [80]:
y_test

array([ 0,  0,  0, ..., 19, 19, 19], shape=(4117,))

In [81]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [82]:
pred = model.predict(X_test)

In [83]:
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score

print("Classification Report:")
print(classification_report(
    y_test,
    pred,
    target_names=encoder.classes_,
    digits=3,
    zero_division=0
))
# print("Confusion Matrix:")
# print(confusion_matrix(y_test, pred))
# print("Precision Score:")
# print(precision_score(y_test, pred, average='weighted'))
# print("Recall Score:")
# print(recall_score(y_test, pred, average='weighted'))
# print("F1 Score:")
# print(f1_score(y_test, pred, average='weighted'))

Classification Report:
                             precision    recall  f1-score   support

             Analyst Update      0.957     0.616     0.750        73
     Company | Product News      0.779     0.898     0.834       852
                 Currencies      0.808     0.656     0.724        32
                   Dividend      0.959     0.969     0.964        97
                   Earnings      0.929     0.917     0.923       242
               Energy | Oil      0.823     0.795     0.808       146
        Fed | Central Banks      0.845     0.818     0.831       214
                 Financials      0.856     0.819     0.837       160
     General News | Opinion      0.742     0.726     0.734       336
  Gold | Metals | Materials      0.529     0.692     0.600        13
                        IPO      0.818     0.643     0.720        14
         Legal | Regulation      0.957     0.739     0.834       119
          M&A | Investments      0.851     0.638     0.729       116
                      Macro      0.796     0.839     0.817       415
                    Markets      0.800     0.736     0.767       125
           Personnel Change      0.924     0.759     0.833       112
                   Politics      0.930     0.847     0.887       249
           Stock Commentary      0.784     0.881     0.830       528
             Stock Movement      0.819     0.690     0.749       197
Treasuries | Corporate Debt      0.931     0.701     0.800        77

                   accuracy                          0.822      4117
                  macro avg      0.842     0.769     0.799      4117
               weighted avg      0.828     0.822     0.821      4117

In [84]:
model_weights = pd.DataFrame(model.coef_, columns=vectorizer.get_feature_names_out(), index=encoder.classes_).T
model_weights

,Analyst Update,Company | Product News,Currencies,Dividend,Earnings,Energy | Oil,Fed | Central Banks,Financials,General News | Opinion,Gold | Metals | Materials,IPO,Legal | Regulation,M&A | Investments,Macro,Markets,Personnel Change,Politics,Stock Commentary,Stock Movement,Treasuries | Corporate Debt
aa,0.576864,-0.100501,-0.014423,-0.007907,-0.126446,-0.029215,-0.031893,-0.006331,-0.098534,-0.010400,-0.004152,-0.022842,-0.027341,-0.195369,-0.092137,-0.023118,-0.029960,0.145083,0.132019,-0.033397
aad,-0.001089,0.102109,-0.000751,-0.000740,-0.001028,-0.001209,-0.001554,-0.001623,-0.043422,-0.000480,-0.000400,-0.005254,-0.002943,-0.001205,-0.001388,-0.026966,-0.002246,-0.004642,-0.003910,-0.001259
aaic,-0.002756,-0.035110,-0.003635,-0.000678,-0.003004,-0.004832,-0.003961,-0.001221,-0.011558,-0.002252,-0.001138,-0.001004,-0.002363,-0.001591,-0.007589,-0.004471,-0.003026,0.140496,-0.047217,-0.003091
aaii,-0.000214,-0.002774,-0.001561,-0.000244,-0.001376,-0.000420,-0.000738,-0.000473,-0.000797,-0.000463,-0.000174,-0.000191,-0.001245,0.111380,-0.000286,-0.000479,-0.000461,-0.098429,-0.000420,-0.000634
aal,-0.155214,0.001165,-0.017413,-0.011824,0.321462,-0.234897,-0.053389,0.075862,-0.258934,-0.012069,-0.007634,-0.038272,-0.061864,-0.246330,-0.070141,-0.087879,-0.047784,0.596776,0.343239,-0.034859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zynerba,-0.000158,-0.008883,-0.000144,-0.000152,-0.000107,-0.000268,-0.000354,-0.000435,-0.002474,-0.000080,-0.000086,-0.003317,-0.013007,-0.000351,-0.000281,-0.000194,-0.000204,-0.000581,0.031655,-0.000579
zynlonta,-0.000074,0.005200,-0.000067,-0.000394,-0.000112,-0.000085,-0.000125,-0.000744,-0.000206,-0.000071,-0.000053,-0.000165,-0.000194,-0.000224,-0.000166,-0.000758,-0.000215,-0.000238,-0.001059,-0.000250
zynx,-0.001879,0.149359,-0.000441,-0.001009,-0.000689,-0.000687,-0.000810,-0.004560,-0.048362,-0.000464,-0.000725,-0.003179,-0.029367,-0.017303,-0.000987,-0.004428,-0.003095,-0.025930,-0.003246,-0.002198
zyus,-0.004767,0.337761,-0.002222,-0.032364,-0.002081,-0.095631,-0.006457,-0.006645,-0.061008,-0.001346,-0.001368,-0.010292,-0.021398,-0.021933,-0.005316,-0.007538,-0.004525,-0.027466,-0.013140,-0.012264
zyversa,-0.004742,-0.012269,-0.001652,-0.000910,-0.001054,-0.001495,-0.001838,-0.003006,-0.015930,-0.000529,0.440022,-0.006279,-0.335937,-0.005524,-0.000758,-0.003682,-0.004331,-0.016606,-0.019941,-0.003541

In [85]:
model_weights.to_csv('model_weights.csv', index=True)